<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAotCompatible>true</IsAotCompatible>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!-- CS1591: Missing XML comment for publicly visible type or member
        CS1573: Parameter has no matching param tag in the XML comment (but other parameters do)
        CA2211: Non-constant (static) fields should not be visible -->
        <NoWarn>1591, 1573, CA2211</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Extended" Version="5.3.1" />
        <PackageReference Include="MonoGame.Extended.Content.Pipeline" Version="5.3.1" />
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
        <ProjectReference Include="..\API\API.csproj" />

        <None Update="Lang/Lang.en-US.properties">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
     <ItemGroup>
    <None Update="Lang/CelosiaLang.en-US.properties">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    </ItemGroup>
</Project>
