# Meta
ModName=Celosia

#region Battle
# Buff names
# Basic
BuffProtect=Protect
BuffStunned=Stunned
BuffRegeneration=Regeneration
BuffExtraAction=Extra Action

# Elemental debuffs
BuffBurn=Burn
BuffFrostbite=Frostbite
BuffShock=Shock
BuffWindswept=Windswept
BuffTremor=Tremor
BuffDazzled=Dazzled
BuffCurse=Curse
BuffPoison=Poison
BuffRadiation=Radiation

# Superior elemental debuffs
BuffBurntOut=Burnt Out
BuffFrostbound=Frostbound
BuffOverloaded=Overloaded
BuffTempest=Tempest
BuffShattered=Shattered
BuffStarstruck=Starstruck
BuffDoomed=Doomed
BuffBlighted=Blighted
BuffDecay=Decay

# Elements
ElementIgnis=Ignis
ElementGlacies=Glacies
ElementFulgur=Fulgur
ElementVentus=Ventus
ElementTerra=Terra
ElementLux=Lux
ElementMalum=Malum

# Mults
MultIgnisDmgDealt=Ignis Dmg Dealt
MultIgnisDmgTaken=Ignis Dmg Taken
MultGlaciesDmgDealt=Glacies Dmg Dealt
MultGlaciesDmgTaken=Glacies Dmg Taken
MultFulgurDmgDealt=Fulgur Dmg Dealt
MultFulgurDmgTaken=Fulgur Dmg Taken
MultVentusDmgDealt=Ventus Dmg Dealt
MultVentusDmgTaken=Ventus Dmg Taken
MultTerraDmgDealt=Terra Dmg Dealt
MultTerraDmgTaken=Terra Dmg Taken
MultLuxDmgDealt=Lux Dmg Dealt
MultLuxDmgTaken=Lux Dmg Taken
MultMalumDmgDealt=Malum Dmg Dealt
MultMalumDmgTaken=Malum Dmg Taken

# Passives todo remove descs
PassiveRestoration=Restoration
PassiveRestorationDesc=

# Change affinities
PassiveIgnisAffUp=Ignis Affinity Up
PassiveIgnisAffUpDesc=

# Change mults
PassivePercentageDmgTakenDown50=Percentage Dmg Taken Down (50%)
PassivePercentageDmgTakenDown50Desc=
PassivePercentageDmgTakenDown999=Percentage Dmg Taken Down (99.9%)
PassivePercentageDmgTakenDown999Desc=

# Change mods
PassiveBuffDurationUp=Buff Duration Up
PassiveBuffDurationUpDesc=
PassiveDebuffDurationUp=Debuff Duration Up
PassiveDebuffDurationUpDesc=

# Change other stats
PassiveEternalWellspring=Eternal Wellspring
PassiveEternalWellspringDesc=

# Skill names
# Basic skills
SkillProtect=Protect
SkillBlossom=Blossom

# Stage changers
SkillAtkUp=Attack Up
SkillAtkDown=Attack Down
SkillDefUp=Defense Up
SkillDefDown=Defense Down
SkillFthUp=Faith Up
SkillFthDown=Faith Down
SkillAgiUp=Agility Up
SkillAgiDown=Agility Down
SkillAtkUpGroup=Group Attack Up
SkillAtkDownGroup=Group Attack Down
SkillDefUpGroup=Group Defense Up
SkillDefDownGroup=Group Defense Down
SkillFthUpGroup=Group Faith Up
SkillFthDownGroup=Group Faith Down
SkillAgiUpGroup=Group Agility Up
SkillAgiDownGroup=Group Agility Down

# Heals
SkillHeal=Heal
SkillAmbrosia=Ambrosia
SkillHealGroup=Group Heal

# Shields
SkillShield=Shield
SkillShieldGroup=Group Shield

# Attacks
# Ignis
# Str
# Mag
SkillFireball=Fireball
SkillHeatWave=Heat Wave

# Glacies
# Str
# Mag
SkillIceBeam=Ice Beam

# Fulgur
# Str
# Mag
SkillThunderbolt=Thunderbolt
SkillChainLightning=Chain Lightning
# todo use FSS word wrap instead of this shit
SkillChainLightningDesc=Hits 3 times. The 1st hits the main target. The 2nd and 3rd\nhits move up or down 1 space, going for a kill if it sees one,\notherwise hitting the target that'll take the most damage.\nDissipates if there’s no valid target above or below.\nEach hit gives {0} {1} /c[white](/c[imp]{2} /c[white]turns)

# Ventus
# Str
SkillJetStream=Jet Stream
# Mag

# Malum
# Str
# Mag
SkillDemonScythe=Demon Scythe

# Bloom skills
# Glacies
SkillIceAge=Ice Age

# Unit types
UnitTypeJohny=Johny
