# Meta
ModName=API

#region Debug

# Modloader info
# 0 = mod property name, 1 = containing file name
ModLoaded=Successfully loaded {0} from {1}

# 0 = loaded mod count, 1 = mod assembly count
AllModsLoaded=Successfully loaded {0} {0,plural,=1{mod}other{mods}} from {1} {0,plural,=1{assembly}other{assemblies}}

#endregion
#region Basic
Blank=
Todo=todo
Yes=Yes
No=No
None=None
Up=Up
Down=Down

#endregion
#region Input
# Keybinds
KeyConfirm=Confirm
KeyBack=Back
KeyMenu1=Menu 1
KeyMenu2=Menu 2
KeyLeft=Left
KeyRight=Right
KeyUp=Up
KeyDown=Down
KeyPageL=Page Left
KeyPageR=Page Right
KeyHotkey1=Hotkey 1
KeyHotkey2=Hotkey 2

# Buttons todo remove if these arent used
ButtonB=B
ButtonA=A
ButtonY=Y
ButtonX=X
# Button{direction} uses key{direction} as its name
ButtonL1=L1
ButtonL2=L2
ButtonR1=R1
ButtonR2=R2
ButtonLm=LM
ButtonRm=RM

# Input prompts
InputConfirm=Confirm
InputBack=Back
InputMove=Move
InputScroll=Scroll
InputClose=Close
InputTop=Top
InputBottom=Bottom
InputLog=Log
InputLogToTopBottom=To Top/Bottom
InputInspect=Inspect
InputChangePage=Change Page
InputChangeUnit=Change Unit
InputInspectStat=Stat Info
InputInspectAffinity=Affinity Info
InputInspectEquip=Equip Info
InputInspectMult=Mult Info
InputInspectMod=Mod Info
InputInspectOther=Other Stat Info

#endregion
#region Themes
ThemeApollo=Apollo
ThemeApolloDesc=todo
ThemeVoid=Void
ThemeVoidDesc=todo
ThemeMikuMikuTheme=MikuMikuTheme
ThemeMikuMikuThemeDesc=todo
ThemeVSCode=VSCode
ThemeVSCodeDesc=todo
ThemeHighContrast=High-Contrast
ThemeHighContrastDesc=todo
ThemeRedMode=RED MODE!!!
ThemeRedModeDesc=todo

#endregion
#region Menu
MenuStart=Start
MenuManual=Manual
MenuOptions=Options
MenuCredits=Credits
MenuQuit=Quit

# Inspect menu
InspectMultipliers=Multipliers
InspectModifiers=Modifiers
InspectOtherStats=Other

#endregion
#region Battle
Skill=Skill
Skills=Skills
Passive=Passive
Passives=Passives
Turn=Turn
Bloom=Bloom
Buff=Buff
Buffs=Buffs
Debuff=Debuff
Debuffs=Debuffs
Affinity=affinity
Affinities=Affinities
PlayerTeam=Player team
OpponentTeam=Opponent team
Immune=Immune
Accessory=Accessory
Accessories=Accessories
Weapon=Weapon
Weapons=Weapons

# CD is short for Cooldown
CD=CD

# Built-in skills and buffs
SkillNothing=Do Nothing
SkillDefend=Defend
BuffDefend=Defend
BuffShield=Defend

# Attack power
Pow=Pow

# Turn order priority
Prio=Prio

# Stats
Stat=Stat
Stats=Stats
StatHp=HP
# todo all .full and .desc keys are currently unused. Make sure to remove everything that's not used by the end
HpFull=Health Points
StatSp=SP
SpFull=Skill Points
StatStr=Str
StatStrFull=Strength
StatMag=Mag
StatMagFull=Magic
StatFth=Fth
StatFthFull=Faith
StatAmr=Amr
StatAmrFull=Armor
StatRes=Res
StatResFull=Resilience
StatAgi=Agi
StatAgiFull=Agility

# Element
ElementVis=Vis

# Multipliers
MultDmgDealt=Dmg Dealt
MultDmgTaken=Dmg Taken
MultWeakDmgDealt=Weakness Dmg Dealt
MultWeakDmgTaken=Weakness Dmg Taken
MultFollowUpDmgDealt=Follow-Up Dmg Dealt
MultFollowUpDmgTaken=Follow-Up Dmg Taken
MultDotDmgTaken=DoT Dmg Taken
MultPercentageDmgTaken=Percentage Dmg Taken
MultHealingDealt=Healing/Shield Given
MultHealingTaken=Healing/Shield Received
MultSpGain=SP Gain
MultSpUse=SP Use

# Modifiers
ModDurationBuffDealt=Buff Given Duration
ModDurationBuffTaken=Buff Received Duration
ModDurationDebuffDealt=Debuff Given Duration
ModDurationDebuffTaken=Debuff Received Duration
ModStacksBuffDealt=Buff Given Stacks
ModStacksBuffTaken=Buff Received Stacks
ModStacksDebuffDealt=Debuff Given Stacks
ModStacksDebuffTaken=Debuff Received Stacks
ModRange=Range

# Boolean stats
BoolEffectBlock=Effect Block
BoolInfiniteSp=Infinite SP
BoolUnableToAct=Unable to Act
BoolUnableToActImmunity=Unable to Act Immunity
BoolEquipDisabled=Equipment Disabled
BoolEquipDisabledImmunity=Equipment Disabled Immunity

# Other stats
ExtraActions=Extra Actions

# Stage types
Stage=stage
Stages=stages
StageAtk=Atk
StageAtkDesc=todo
StageDef=Def
StageDefDesc=todo
# The other stage type names use the same lang as stats
StageFthDesc=todo
StageAgiDesc=todo

# Skill types
# The other skill types use the same lang as stats
SkillTypeStat=Stat
SkillTypeStatFull=Status

# Ranges
# R stands for Range
# todo descs?
RangeSelf=Self
RangeOther1R=Other 1R
RangeOther2R=Other 2R
RangeOther3R=Any Other
RangeOther1ROrSelf=Other 1R or Self
RangeOther2ROrSelf=Other 2R or Self
RangeOther3ROrSelf=Any
RangeOthers21R=2 Others 1R
RangeOthers22R=2 Others 2R
RangeOthers23R=Any 2 Others
RangeAlly1R=Ally 1R
RangeAlly2R=Ally 2R
RangeAlly3R=Any Ally
RangeAllies21R=2 Allies 1R
RangeAllies22R=2 Allies 2R
RangeAllies23R=Any 2 Allies
RangeOpponent1R=Opponent 1R
RangeOpponent2R=Opponent 2R
RangeOpponent3R=Any Opponent
RangeTeam=Team
RangeAll=All
RangeAllOthers=All Others
RangeAdjacent=Adjacent
RangeSelfUpDown=Self+Up+Down
RangeAcross=Across
RangeAcrossUpDown=Across+Up+Down
RangeColumnOf31R=Column of 3 1R
RangeColumnOf32R=Column of 3 2R

# Unit types
TestUnitType=Test UnitType

#endregion
#region Battle Log
LogGainSpBloom=All units gain /c[sp]100 /c[stat]SP/c[white]; both teams gain /c[bloom]100 /c[stat]Bloom

# BuffEffects
# 0 = name, 1 = element name, 2 = old aff, 3 = new aff
# Name's element affinity +5 → +6
LogChangeAff={0} {1} /c[stat]affinity {2} /c[white]→ {3}

# 0 = side ID, 1 = old bloom, 2 = new bloom, 3 = change
# Player/Opponent Team Bloom a → b (+c)
LogChangeBloom={0,plural,=0{Player}=1{Opponent}} team /c[stat]Bloom {1} /c[white]→ {2} /c[white]({3}/c[white])

# ChangeBooleanStat
# 0 = name, 1 = value (0 = false, other = true)
# Name is no longer/now immune to x
LogChangeBooleanStatEffectBlock={0} {1,plural,=0{is no longer}other{is now}} immune to secondary skill effects
LogChangeBooleanStatUnableToActImmune={0} {1,plural,=0{is no longer}other{is now}} immune to becoming unable to act
LogChangeBooleanStatEquipDisabledImmune={0} {1,plural,=0{is no longer}other{is now}} immune to having their equipment disabled

# 2 = SP
# Name's SP a → b
LogChangeBooleanStatInfiniteSp={0} /c[stat]SP /c[sp]{1,plural,=0{∞}other{{2}}} /c[white]→ /c[sp]{1,plural,=0{{2}}other{∞}}

# Name is no longer/now unable to act
LogChangeBooleanStatUnableToAct={0} {1,plural,=0{is no longer}other{is now}} unable to act

# Name's equipment is no longer/now disabled
LogChangeBooleanStatEquipDisabled={0} equipment {1,plural,=0{is no longer}other{is now}} disabled

# 0 = name, 1 = old extra actions, 2 = new extra actions
# Name's Extra Actions a → b
LogChangeExtraActions={0} Extra Actions {1} /c[white]→ {2}

# 0 = name, 1 = old HP, 2 = new HP, 3 = max HP, 4 = change
# Name's HP a → b/c (+d)
LogChangeHp={0} /c[stat]HP {1} /c[white]→ {2}/c[white]//{3} /c[white]({4}/c[white])

# 0 = name, 1 = old SP, 2 = new SP, 3 = change
# Name's SP a → b (+c)
LogChangeSp={0} /c[stat]SP {1} /c[white]→ {2} /c[white]({3}/c[white])

# 0 = name, 1 = mod name, 2 = old mod, 3 = new mod
# Name's mod +a → +b
LogChangeMod={0} {1} {2} /c[white]→ {3}

# 0 = name, 1 = mult name, 2 = old mult, 3 = new mult, 4 = mult change
# Name's mult a% → b% (+c%)
LogChangeMult={0} {1} {2} /c[white]→ {3} /c[white]({4})

# 0 = name, 1 = old shield, 2 = new shield, 3 = max HP, 4 = shield change
# Name's shield a → b/c (+d)
LogChangeShield={0} /c[shield][+vibrating-shield]/c[buff]Shield {1} /c[white]→ {2}/c[white]/{3} /c[white]({4}/c[white])

# 0 = name, 1 = stage name, 2 = old stage, 3 = new stage
# Name's Atk/Def/Fth/Agi Stage +a → +b
LogChangeStageStacks={0} {1} /c[white]Stage {2} /c[white]→ {3}

# 0 = name, 1 = stage name, 2 = old turns, 3 = new turns
# Name's Atk/Def/Fth/Agi Stage turns a → b
LogChangeStageTurns={0} {1} Stage turns {2} /c[white] → {3}

# 0 = name, 1 = stat name, 2 = old stat, 3 = new stat, 4 = default stat, 5 = change
# Name's stat a → b/c (+d)
LogChangeStat={0} {1} {2} /c[white]→ {3}/c[white]//{4} /c[white]({5}/c[white])

# 0 = name, 1 = buff name, 2 = old stacks, 3 = new stacks
# Name's buff stacks a → b
LogGiveBuffStacks={0} {1} /c[white]stacks {2} /c[white]→ {3}

# 0 = name, 1 = buff name, 2 = old turns, 3 = new turns
# Name's buff turns a → b
LogGiveBuffTurns={0} {1} /c[white]turns {2} /c[white]→ {3}

# 0 = name, 1 = buff name, 2 = buff max stacks, 3 = display-formatted stacks, 4 = raw stacks, 5 = display-formatted turns, 6 = raw turns
# Max stacks > 1: Name gains buff with a stacks and b turns
# Max stacks = 1: Name gains buff for b turns
LogGiveBuffGain={0} gains {1} /c[white]{2,plural,=1{for}other{with {3} /c[white]/c[white]{4,plural,=1{stack}other{stacks}} and}} {5} /c[white]{6,plural,=1{turn}other{turns}}

# 0 = name, 1 = max stacks, 2 = display-formatted stacks, 3 = buff name, 4 = raw stacks
# Max stacks > 1: Name loses 3 buff stacks
# Max stacks = 1: Name loses buff
LogLoseBuff={0} /c[white]loses {1,plural,=2{{2} }other{}}{3} {1,plural,=2{{4,plural,=1{stack}other{stacks}}}other{}}

# 0 = name, 1 = stages, 2 = display-formatted stages, 3 = stage name, 4 = stageStatString
# Name loses a Atk/Def/Fth/Agi stage(s) (stageStatString)
LogLoseStage={0} /c[white]loses {2} {3} /c[white]{1,plural,=1{stage}=-1{stage}other{stages}} {4}

# 0 = name, 1 = shield
# Name loses a Shield
LogLoseShield={0} /c[white]loses {1} /c[buff]Shield

# 0 = name, 1 = old turns, 2 = new turns
# Name's Shield turns a → b
LogShieldTurns={0} /c[buff]Shield /c[white]turns {1} /c[white]→ {2}

# 0 = stat name, 1 = old stat, 2 = new stat, 3 = base stat, 4 = change
# stat a → b/c (+d)
LogStageStat={0} {1} /c[white]→ {2}/c[white]/{3} /c[white]({4}/c[white])

# 0 = name, 1 = buff/passive name
# Name's buff/passive:
LogTurnEndEffect={0} {1}/c[white]:

# Used for Buffs, Shields, and Stages
# 0 = old turns, 1 = new turns
# , turns a → b
LogTurnsNameless=/c[white], turns {0} /c[white] → {1}

# Skill use
# 0 = name, 1 = skill name, 2 = target name, 3 = isRangeSelf (0 = false, other = true), 4 = LogSkillUseChangeSpBloom
# Name uses skill on name (SP/Bloom a → b (+c))
LogSkillUse={0} /c[white]uses {1} /c[white]{3,plural,=0{on {2} }other{}}{4}

# 0 = isBloom (0 = false, other = true), 1 = old SP/Bloom, 2 = new SP/Bloom, 3 = SP/Bloom change
# (SP a → b (+c))
LogSkillUseChangeSpBloom=/c[white] (/c[stat]{0,plural,=0{SP}other{Bloom}} {1} /c[white]→ {2} /c[white]({3}/c[white]))

# 0 = name
# No effect on Name
LogNoEffect=/c[neg]No effect /c[white]on {0}

# 0 = name, 1 = skill name
# Name tries to use skill
LogTriesToUse1={0} tries to use {1}

# 0 = name
# on Name
LogTriesToUse2=/c[white] on {0}

LogButIsUnableToAct=, but is unable to act

# 0 = LogTriesToUse1 and 2, 1 = LogButIsUnableToAct
# Name tries to use skill on Name, but is unable to act
LogSkillFailUnableToAct={0}/c[white]{1}

# 0 = cooldown
# , but it's on cooldown (a turns)
LogButItsOnCooldown=, but it's on cooldown (/c[cooldown]{0} {0,plural,=1{turn}other{turns}}/c[white])

# 0 = log.tries_to_use.1 and 2, 1 = log.but_its_on_cooldown
# Name tries to use skill on Name, but it's on cooldown (a turns)
LogSkillFailCooldown={0}/c[white]{1}

LogButCantReach=, but can't reach

# 0 = LogTriesToUse1 and 2, 1 = LogButCantReach
# Name tries to use skill on Name, but can't reach
LogSkillFailRange={0}/c[white]{1}

# 0 = isBloom (0 = false, other = true)
# , but doesn't have enough SP/Bloom
LogButDoesntHaveEnough=, but doesn't have enough /c[#{0,plural,=0{bb00ff]SP}other{ff00ff]Bloom}}

# 0 = LogTriesToUse1 and 2, 1 = LogButDoesntHaveEnough
# Name tries to use skill on Name, but doesn't have enough SP/Bloom
LogSkillFailSp={0}/c[white]{1}

# Skill descriptions
# 0 = cost
SkillCostSP={0} SP
SkillCostBloom={0} Bloom

# 0 = SkillType, 1 = element, 2 = range, 3 = , pow (if applicable), 4 = , prio (if applicable), 5 = skill_desc body
# Str, Ignis, Other 1R, 50 Pow
# (skill description)
SkillDesc={0}, {1}/c[white], {2}{3}{4}\n/c[white]{5}

# 0 = stacks, 1 = buff, 2 = turns
# Gives +a Buff (b turns)
SkillDescBuff=Gives {0} {1} /c[white](/c[imp]{2} /c[white]turns)

# 0 = stacks1, 1 = buff1, 2 = stacks2, 3 = buff2, 4 = turns
# Gives +a Buff1 and +b Buff2 (c turns)
SkillDescBuff2SameTurns=Gives {0}{1} /c[white]and {2}{3} /c[white](/c[imp]{4} /c[white]turns)

# 0 = hits, 1 = stacks, 2 = buff, 3 = turns
# Hits a times. Each hit gives +b Buff (c turns)
SkillDescMultihitBuff=Hits /c[imp]{0} /c[white]times. Each hit gives {1} {2} /c[white](/c[imp]{3} /c[white]turns)

# Buff descriptions
# todo inline
# 0 = (De)Buff, 1 = ", Stacks to a" or nothing, 2 = Description
# (De)Buff, Stacks to a. (description)
BuffDesc={0}{1}/c[white]\n{2}

# 0 = max stacks
BuffDescStacksTo=, stacks to {0}

# 0 = (thing), 1 = (thing)
BuffDesc1={0}
BuffDesc2={0} /c[white]and {1}
BuffDesc1PerStack={0} /c[white]per stack
BuffDesc2PerStack={0} /c[white]and {1} /c[white]per stack
BuffDesc2PerStackHp={0} HP /c[white]each turn and {1} /c[white]per stack

# Accessory descriptions
# 0 = desc
AccessoryDesc=Accessory. Gives the following:\n{0}

AccessoryFirebornRing=Fireborn Ring

# Weapon descriptions
# 0 = desc
WeaponDesc=Weapon. Gives the following:\n{0}
#endregion

#region Info
# Popups/tutorials
TutorialDamage=Damage
TutorialDamageDesc=Damage is calculated with the following formula:\nAtk = User's Str or Mag, depending on the skill's type\nDef = Target's Amr or Res, depending on the skill's type\nDamage = (Atk / Def) * (pow * 10) * damage modifier for user's affinity * damage modifier for target's affinity * user's Dmg Dealt * target's Dmg Taken * user's (Element) Dmg Dealt * target's (Element) Dmg Dealt * (if hitting a weakness) user's Weakness Dmg Dealt * target's Weakness Dmg Taken * (if the skill is a Follow-Up) user's Follow-Up Dmg Dealt * target's Follow-Up Dmg Taken
InfoStat=Stats
InfoStatDesc=todo
InfoAffinity=Affinity
InfoAffinityDesc=todo
InfoMult=Multipliers
InfoMultDesc=todo
InfoMod=Modifiers
InfoModDesc=todo
InfoOther=Other Stats
InfoOtherDesc=todo
WarningInvalidMove=Invalid Move
WarningInvalidMoveDesc=The move you have selected is invalid because {REASON}\nThe move may become valid before it executes, but if not, it will fail\nAre you sure you want to select this move?\n(This warning can be disabled in the Settings)
WarningInvalidMoveIsOutOfRange=is out of range
WarningInvalidMoveDoesntHaveEnough=doesn't have enough