Name=Apollo
Desc=Apollo
UseLangKey=true

Fg=#edede9
Midtone=#819796
Bg=#10141f
BgSecondary=#ff0000
BgTrans=#090a14a0

Accent=#253a5e
AccentDeemphasized=#ff0000

Positive=#468232
Negative=#cf573c
Emphasis=#d0da91
Ally=#4f8fba
Opponent=#a53030
Turn=#c65197
Hp=#75a743
Sp=#a23e8c
Shield=#73bed3
Bloom=#df84a5
Buff=#df84a5
Skill=#73bed3
Element=#73bed3
Passive=#df84a5
Stat=#a4dddb
Reticle=#ff0000
Cooldown=#4f8fba

SpBack=#df84a5
Overheal=#c65197
StatBarLayer4=#a4dddb
StatBarLayer5=#df84a5

Atk=#a53030
Def=#4f8fba
Fth=#402751
Agi=#468232

Vis=#a8b5b2
Ignis=#da863e
Glacies=#73bed3
Fulgur=#e8c170
Ventus=#468232
Terra=#ad7757
Lux=#e7d5b3
Malum=#cf573c
