Name=HighContrast
Desc=HighContrast
UseLangKey=true

Fg=#ffffff
Midtone=#808080
Bg=#000000
BgSecondary=#ff0000
BgTrans=#000000a0

Accent=#a020f0
AccentDeemphasized=#ff0000

Positive=#00ff00
Negative=#ff5151
Emphasis=#ffff00
Ally=#83aaf0
Opponent=#ff7474
Turn=#a034ff
Hp=#1ae132
Sp=#bb00ff
Shield=#00ffff
Bloom=#ff00ff
Buff=#c6a1ff
Skill=#95c9ff
Element=#95c9ff
Passive=#c6a1ff
Stat=#deff81
Reticle=#ff0000
Cooldown=#1898ff

SpBack=#d78bff
Overheal=#ee82ef
StatBarLayer4=#00ffff
StatBarLayer5=#ffc0cb

Atk=#ff5151
Def=#1898ff
Fth=#b556ee
Agi=#90ee90

Vis=#d3d3d3
Ignis=#ffa500
Glacies=#add8e6
Fulgur=#ffff00
Ventus=#00ff00
Terra=#f4a460
Lux=#fffbb7
Malum=#ff0000
