Name=MikuMikuTheme
Desc=MikuMikuTheme
UseLangKey=true

Fg=#d6ecf9
Midtone=#a0a0a0
Bg=#1f1f1f
BgSecondary=#ff0000
BgTrans=#1f1f1fa0

Accent=#336699
AccentDeemphasized=#ff0000

Positive=#51acb6
Negative=#ec83a8
Emphasis=#b6dbca
Ally=#89cdc6
Opponent=#e3004f
Turn=#e8418f
Hp=#b6dbca
Sp=#e8418f
Shield=#89cdc6
Bloom=#e8418f
Buff=#338397
Skill=#338397
Element=#338397
Passive=#338397
Stat=#d3d3cc
Reticle=#ff0000
Cooldown=#336699

SpBack=#ec83a8
Overheal=#ec83a8
StatBarLayer4=#89cdc6
StatBarLayer5=#ec83a8

Atk=#e3004f
Def=#336699
Fth=#e8418f
Agi=#b6dbca

Vis=#a0a0a0
Ignis=#ec83a8
Glacies=#51acb6
Fulgur=#d3d3cc
Ventus=#b6dbca
Terra=#9f9294
Lux=#89cdc6
Malum=#e3004f
