Name=VSCode
Desc=VSCode
UseLangKey=true

Fg=#fef5f7
Midtone=#a0a0a0
Bg=#1f1f1f
BgSecondary=#ff0000
BgTrans=#1f1f1fa0

Accent=#0877d3
AccentDeemphasized=#ff0000

Positive=#4ec9b0
Negative=#d16969
Emphasis=#dcdcaa
Ally=#9cdcfe
Opponent=#d16969
Turn=#c586c0
Hp=#b5cea8
Sp=#9cdcfe
Shield=#9cdcfe
Bloom=#d96fd5
Buff=#5798d2
Skill=#4ec9b0
Element=#4ec9b0
Passive=#5798d2
Stat=#dcdcaa
Reticle=#ff0000
Cooldown=#1e99f5

SpBack=#d96fd5
Overheal=#c586c0
StatBarLayer4=#1e99f5
StatBarLayer5=#d96fd5

Atk=#d16969
Def=#4fc1ff
Fth=#c586c0
Agi=#4ec9b0

Vis=#a0a0a0
Ignis=#d16969
Glacies=#4fc1ff
Fulgur=#ffd606
Ventus=#b5cea8
Terra=#ce9178
Lux=#dcdcaa
Malum=#c586c0
