<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>Preview</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="FontStashSharp.MonoGame" Version="1.4.1"/>
        <PackageReference Include="MessageFormat" Version="7.1.3" />
        <PackageReference Include="MonoGame.Extended" Version="5.1.0"/>
        <PackageReference Include="MonoGame.Extended.Content.Pipeline" Version="5.1.0"/>
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Lang.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Lang.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Lang.de-DE.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Lang.de-DE.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Lang.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Lang.resx</DependentUpon>
        </Compile>
        <Compile Update="Lang.de-DE.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Lang.de-DE.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    <Target Name="GenerateBuildDate" BeforeTargets="BeforeCompile">
        <PropertyGroup>
            <BuildDate>$([System.DateTime]::Now.ToString("dd-MM-yyyy"))</BuildDate>
            <Semicolon>test;</Semicolon>
        </PropertyGroup>
        <WriteLinesToFile File="BuildInfo.cs" Lines="//------------------------------------------------------------------------------%0A// %3C/auto-generated%3E%0A//     This code was generated by a tool.%0A//%0A//     Changes to this file may cause incorrect behavior and will be lost if%0A//     the code is regenerated.%0A// %3C/auto-generated%3E%0A//------------------------------------------------------------------------------%0Anamespace API%3B%0A%0Apublic static class BuildInfo {%0A    public const string BuildDate = &quot;$(BuildDate)&quot;%3B%0A}" Overwrite="true"/>
    </Target>
</Project>