//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("API.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        public static string Todo {
            get {
                return ResourceManager.GetString("Todo", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        public static string DebugInfoL {
            get {
                return ResourceManager.GetString("DebugInfoL", resourceCulture);
            }
        }
        
        public static string DebugInfoR {
            get {
                return ResourceManager.GetString("DebugInfoR", resourceCulture);
            }
        }
        
        public static string KeyConfirm {
            get {
                return ResourceManager.GetString("KeyConfirm", resourceCulture);
            }
        }
        
        public static string KeyBack {
            get {
                return ResourceManager.GetString("KeyBack", resourceCulture);
            }
        }
        
        public static string KeyMenu {
            get {
                return ResourceManager.GetString("KeyMenu", resourceCulture);
            }
        }
        
        public static string KeyMap {
            get {
                return ResourceManager.GetString("KeyMap", resourceCulture);
            }
        }
        
        public static string KeyLeft {
            get {
                return ResourceManager.GetString("KeyLeft", resourceCulture);
            }
        }
        
        public static string KeyRight {
            get {
                return ResourceManager.GetString("KeyRight", resourceCulture);
            }
        }
        
        public static string KeyUp {
            get {
                return ResourceManager.GetString("KeyUp", resourceCulture);
            }
        }
        
        public static string KeyDown {
            get {
                return ResourceManager.GetString("KeyDown", resourceCulture);
            }
        }
        
        public static string KeyPageL1 {
            get {
                return ResourceManager.GetString("KeyPageL1", resourceCulture);
            }
        }
        
        public static string KeyPageL2 {
            get {
                return ResourceManager.GetString("KeyPageL2", resourceCulture);
            }
        }
        
        public static string KeyPageR1 {
            get {
                return ResourceManager.GetString("KeyPageR1", resourceCulture);
            }
        }
        
        public static string KeyPageR2 {
            get {
                return ResourceManager.GetString("KeyPageR2", resourceCulture);
            }
        }
        
        public static string ButtonB {
            get {
                return ResourceManager.GetString("ButtonB", resourceCulture);
            }
        }
        
        public static string ButtonA {
            get {
                return ResourceManager.GetString("ButtonA", resourceCulture);
            }
        }
        
        public static string ButtonY {
            get {
                return ResourceManager.GetString("ButtonY", resourceCulture);
            }
        }
        
        public static string ButtonX {
            get {
                return ResourceManager.GetString("ButtonX", resourceCulture);
            }
        }
        
        public static string ButtonL1 {
            get {
                return ResourceManager.GetString("ButtonL1", resourceCulture);
            }
        }
        
        public static string ButtonL2 {
            get {
                return ResourceManager.GetString("ButtonL2", resourceCulture);
            }
        }
        
        public static string ButtonR1 {
            get {
                return ResourceManager.GetString("ButtonR1", resourceCulture);
            }
        }
        
        public static string ButtonR2 {
            get {
                return ResourceManager.GetString("ButtonR2", resourceCulture);
            }
        }
        
        public static string ButtonLm {
            get {
                return ResourceManager.GetString("ButtonLm", resourceCulture);
            }
        }
        
        public static string ButtonRm {
            get {
                return ResourceManager.GetString("ButtonRm", resourceCulture);
            }
        }
        
        public static string InputConfirm {
            get {
                return ResourceManager.GetString("InputConfirm", resourceCulture);
            }
        }
        
        public static string InputBack {
            get {
                return ResourceManager.GetString("InputBack", resourceCulture);
            }
        }
        
        public static string InputMove {
            get {
                return ResourceManager.GetString("InputMove", resourceCulture);
            }
        }
        
        public static string InputClose {
            get {
                return ResourceManager.GetString("InputClose", resourceCulture);
            }
        }
        
        public static string InputTop {
            get {
                return ResourceManager.GetString("InputTop", resourceCulture);
            }
        }
        
        public static string InputBottom {
            get {
                return ResourceManager.GetString("InputBottom", resourceCulture);
            }
        }
        
        public static string InputLog {
            get {
                return ResourceManager.GetString("InputLog", resourceCulture);
            }
        }
        
        public static string InputInspect {
            get {
                return ResourceManager.GetString("InputInspect", resourceCulture);
            }
        }
        
        public static string InputInspectStat {
            get {
                return ResourceManager.GetString("InputInspectStat", resourceCulture);
            }
        }
        
        public static string InputInspectAffinity {
            get {
                return ResourceManager.GetString("InputInspectAffinity", resourceCulture);
            }
        }
        
        public static string InputInspectEquip {
            get {
                return ResourceManager.GetString("InputInspectEquip", resourceCulture);
            }
        }
        
        public static string InputInspectMult {
            get {
                return ResourceManager.GetString("InputInspectMult", resourceCulture);
            }
        }
        
        public static string InputInspectMod {
            get {
                return ResourceManager.GetString("InputInspectMod", resourceCulture);
            }
        }
        
        public static string InputInspectOther {
            get {
                return ResourceManager.GetString("InputInspectOther", resourceCulture);
            }
        }
        
        public static string MenuStart {
            get {
                return ResourceManager.GetString("MenuStart", resourceCulture);
            }
        }
        
        public static string MenuManual {
            get {
                return ResourceManager.GetString("MenuManual", resourceCulture);
            }
        }
        
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        public static string MenuCredits {
            get {
                return ResourceManager.GetString("MenuCredits", resourceCulture);
            }
        }
        
        public static string MenuQuit {
            get {
                return ResourceManager.GetString("MenuQuit", resourceCulture);
            }
        }
        
        public static string InspectMultipliers {
            get {
                return ResourceManager.GetString("InspectMultipliers", resourceCulture);
            }
        }
        
        public static string InspectModifiers {
            get {
                return ResourceManager.GetString("InspectModifiers", resourceCulture);
            }
        }
        
        public static string InspectOtherStats {
            get {
                return ResourceManager.GetString("InspectOtherStats", resourceCulture);
            }
        }
        
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        public static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        public static string Passives {
            get {
                return ResourceManager.GetString("Passives", resourceCulture);
            }
        }
        
        public static string Turn {
            get {
                return ResourceManager.GetString("Turn", resourceCulture);
            }
        }
        
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        public static string Bloom {
            get {
                return ResourceManager.GetString("Bloom", resourceCulture);
            }
        }
        
        public static string Buff {
            get {
                return ResourceManager.GetString("Buff", resourceCulture);
            }
        }
        
        public static string Buffs {
            get {
                return ResourceManager.GetString("Buffs", resourceCulture);
            }
        }
        
        public static string Debuff {
            get {
                return ResourceManager.GetString("Debuff", resourceCulture);
            }
        }
        
        public static string Debuffs {
            get {
                return ResourceManager.GetString("Debuffs", resourceCulture);
            }
        }
        
        public static string Affinity {
            get {
                return ResourceManager.GetString("Affinity", resourceCulture);
            }
        }
        
        public static string Affinities {
            get {
                return ResourceManager.GetString("Affinities", resourceCulture);
            }
        }
        
        public static string PlayerTeam {
            get {
                return ResourceManager.GetString("PlayerTeam", resourceCulture);
            }
        }
        
        public static string OpponentTeam {
            get {
                return ResourceManager.GetString("OpponentTeam", resourceCulture);
            }
        }
        
        public static string Immune {
            get {
                return ResourceManager.GetString("Immune", resourceCulture);
            }
        }
        
        public static string Pow {
            get {
                return ResourceManager.GetString("Pow", resourceCulture);
            }
        }
        
        public static string Prio {
            get {
                return ResourceManager.GetString("Prio", resourceCulture);
            }
        }
        
        public static string ElementVis {
            get {
                return ResourceManager.GetString("ElementVis", resourceCulture);
            }
        }
        
        public static string ElementVisDesc {
            get {
                return ResourceManager.GetString("ElementVisDesc", resourceCulture);
            }
        }
        
        public static string ElementIgnis {
            get {
                return ResourceManager.GetString("ElementIgnis", resourceCulture);
            }
        }
        
        public static string ElementIgnisDesc {
            get {
                return ResourceManager.GetString("ElementIgnisDesc", resourceCulture);
            }
        }
        
        public static string ElementGlacies {
            get {
                return ResourceManager.GetString("ElementGlacies", resourceCulture);
            }
        }
        
        public static string ElementGlaciesDesc {
            get {
                return ResourceManager.GetString("ElementGlaciesDesc", resourceCulture);
            }
        }
        
        public static string ElementFulgur {
            get {
                return ResourceManager.GetString("ElementFulgur", resourceCulture);
            }
        }
        
        public static string ElementFulgurDesc {
            get {
                return ResourceManager.GetString("ElementFulgurDesc", resourceCulture);
            }
        }
        
        public static string ElementVentus {
            get {
                return ResourceManager.GetString("ElementVentus", resourceCulture);
            }
        }
        
        public static string ElementVentusDesc {
            get {
                return ResourceManager.GetString("ElementVentusDesc", resourceCulture);
            }
        }
        
        public static string ElementTerra {
            get {
                return ResourceManager.GetString("ElementTerra", resourceCulture);
            }
        }
        
        public static string ElementTerraDesc {
            get {
                return ResourceManager.GetString("ElementTerraDesc", resourceCulture);
            }
        }
        
        public static string ElementLux {
            get {
                return ResourceManager.GetString("ElementLux", resourceCulture);
            }
        }
        
        public static string ElementLuxDesc {
            get {
                return ResourceManager.GetString("ElementLuxDesc", resourceCulture);
            }
        }
        
        public static string ElementMalum {
            get {
                return ResourceManager.GetString("ElementMalum", resourceCulture);
            }
        }
        
        public static string ElementMalumDesc {
            get {
                return ResourceManager.GetString("ElementMalumDesc", resourceCulture);
            }
        }
        
        public static string Stat {
            get {
                return ResourceManager.GetString("Stat", resourceCulture);
            }
        }
        
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        public static string Hp {
            get {
                return ResourceManager.GetString("Hp", resourceCulture);
            }
        }
        
        public static string HpFull {
            get {
                return ResourceManager.GetString("HpFull", resourceCulture);
            }
        }
        
        public static string Sp {
            get {
                return ResourceManager.GetString("Sp", resourceCulture);
            }
        }
        
        public static string SpFull {
            get {
                return ResourceManager.GetString("SpFull", resourceCulture);
            }
        }
        
        public static string StatStr {
            get {
                return ResourceManager.GetString("StatStr", resourceCulture);
            }
        }
        
        public static string StatStrFull {
            get {
                return ResourceManager.GetString("StatStrFull", resourceCulture);
            }
        }
        
        public static string StatMag {
            get {
                return ResourceManager.GetString("StatMag", resourceCulture);
            }
        }
        
        public static string StatMagFull {
            get {
                return ResourceManager.GetString("StatMagFull", resourceCulture);
            }
        }
        
        public static string StatFth {
            get {
                return ResourceManager.GetString("StatFth", resourceCulture);
            }
        }
        
        public static string StatFthFull {
            get {
                return ResourceManager.GetString("StatFthFull", resourceCulture);
            }
        }
        
        public static string StatAmr {
            get {
                return ResourceManager.GetString("StatAmr", resourceCulture);
            }
        }
        
        public static string StatAmrFull {
            get {
                return ResourceManager.GetString("StatAmrFull", resourceCulture);
            }
        }
        
        public static string StatRes {
            get {
                return ResourceManager.GetString("StatRes", resourceCulture);
            }
        }
        
        public static string StatResFull {
            get {
                return ResourceManager.GetString("StatResFull", resourceCulture);
            }
        }
        
        public static string StatAgi {
            get {
                return ResourceManager.GetString("StatAgi", resourceCulture);
            }
        }
        
        public static string StatAgiFull {
            get {
                return ResourceManager.GetString("StatAgiFull", resourceCulture);
            }
        }
        
        public static string MultDmgDealt {
            get {
                return ResourceManager.GetString("MultDmgDealt", resourceCulture);
            }
        }
        
        public static string MultDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultDmgTaken {
            get {
                return ResourceManager.GetString("MultDmgTaken", resourceCulture);
            }
        }
        
        public static string MultDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultIgnisDmgDealt {
            get {
                return ResourceManager.GetString("MultIgnisDmgDealt", resourceCulture);
            }
        }
        
        public static string MultIgnisDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultIgnisDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultIgnisDmgTaken {
            get {
                return ResourceManager.GetString("MultIgnisDmgTaken", resourceCulture);
            }
        }
        
        public static string MultIgnisDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultIgnisDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultGlaciesDmgDealt {
            get {
                return ResourceManager.GetString("MultGlaciesDmgDealt", resourceCulture);
            }
        }
        
        public static string MultGlaciesDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultGlaciesDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultGlaciesDmgTaken {
            get {
                return ResourceManager.GetString("MultGlaciesDmgTaken", resourceCulture);
            }
        }
        
        public static string MultGlaciesDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultGlaciesDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultFulgurDmgDealt {
            get {
                return ResourceManager.GetString("MultFulgurDmgDealt", resourceCulture);
            }
        }
        
        public static string MultFulgurDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultFulgurDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultFulgurDmgTaken {
            get {
                return ResourceManager.GetString("MultFulgurDmgTaken", resourceCulture);
            }
        }
        
        public static string MultFulgurDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultFulgurDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultVentusDmgDealt {
            get {
                return ResourceManager.GetString("MultVentusDmgDealt", resourceCulture);
            }
        }
        
        public static string MultVentusDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultVentusDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultVentusDmgTaken {
            get {
                return ResourceManager.GetString("MultVentusDmgTaken", resourceCulture);
            }
        }
        
        public static string MultVentusDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultVentusDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultTerraDmgDealt {
            get {
                return ResourceManager.GetString("MultTerraDmgDealt", resourceCulture);
            }
        }
        
        public static string MultTerraDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultTerraDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultTerraDmgTaken {
            get {
                return ResourceManager.GetString("MultTerraDmgTaken", resourceCulture);
            }
        }
        
        public static string MultTerraDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultTerraDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultLuxDmgDealt {
            get {
                return ResourceManager.GetString("MultLuxDmgDealt", resourceCulture);
            }
        }
        
        public static string MultLuxDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultLuxDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultLuxDmgTaken {
            get {
                return ResourceManager.GetString("MultLuxDmgTaken", resourceCulture);
            }
        }
        
        public static string MultLuxDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultLuxDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultMalumDmgDealt {
            get {
                return ResourceManager.GetString("MultMalumDmgDealt", resourceCulture);
            }
        }
        
        public static string MultMalumDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultMalumDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultMalumDmgTaken {
            get {
                return ResourceManager.GetString("MultMalumDmgTaken", resourceCulture);
            }
        }
        
        public static string MultMalumDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultMalumDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultWeakDmgDealt {
            get {
                return ResourceManager.GetString("MultWeakDmgDealt", resourceCulture);
            }
        }
        
        public static string MultWeakDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultWeakDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultWeakDmgTaken {
            get {
                return ResourceManager.GetString("MultWeakDmgTaken", resourceCulture);
            }
        }
        
        public static string MultWeakDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultWeakDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultFollowUpDmgDealt {
            get {
                return ResourceManager.GetString("MultFollowUpDmgDealt", resourceCulture);
            }
        }
        
        public static string MultFollowUpDmgDealtDesc {
            get {
                return ResourceManager.GetString("MultFollowUpDmgDealtDesc", resourceCulture);
            }
        }
        
        public static string MultFollowUpDmgTaken {
            get {
                return ResourceManager.GetString("MultFollowUpDmgTaken", resourceCulture);
            }
        }
        
        public static string MultFollowUpDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultFollowUpDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultDotDmgTaken {
            get {
                return ResourceManager.GetString("MultDotDmgTaken", resourceCulture);
            }
        }
        
        public static string MultDotDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultDotDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultPercentageDmgTaken {
            get {
                return ResourceManager.GetString("MultPercentageDmgTaken", resourceCulture);
            }
        }
        
        public static string MultPercentageDmgTakenDesc {
            get {
                return ResourceManager.GetString("MultPercentageDmgTakenDesc", resourceCulture);
            }
        }
        
        public static string MultHealingDealt {
            get {
                return ResourceManager.GetString("MultHealingDealt", resourceCulture);
            }
        }
        
        public static string MultHealingDealtDesc {
            get {
                return ResourceManager.GetString("MultHealingDealtDesc", resourceCulture);
            }
        }
        
        public static string MultHealingTaken {
            get {
                return ResourceManager.GetString("MultHealingTaken", resourceCulture);
            }
        }
        
        public static string MultHealingTakenDesc {
            get {
                return ResourceManager.GetString("MultHealingTakenDesc", resourceCulture);
            }
        }
        
        public static string MultSpGain {
            get {
                return ResourceManager.GetString("MultSpGain", resourceCulture);
            }
        }
        
        public static string MultSpGainDesc {
            get {
                return ResourceManager.GetString("MultSpGainDesc", resourceCulture);
            }
        }
        
        public static string MultSpUse {
            get {
                return ResourceManager.GetString("MultSpUse", resourceCulture);
            }
        }
        
        public static string MultSpUseDesc {
            get {
                return ResourceManager.GetString("MultSpUseDesc", resourceCulture);
            }
        }
        
        public static string ModDurationBuffDealt {
            get {
                return ResourceManager.GetString("ModDurationBuffDealt", resourceCulture);
            }
        }
        
        public static string ModDurationBuffTaken {
            get {
                return ResourceManager.GetString("ModDurationBuffTaken", resourceCulture);
            }
        }
        
        public static string ModDurationDebuffDealt {
            get {
                return ResourceManager.GetString("ModDurationDebuffDealt", resourceCulture);
            }
        }
        
        public static string ModDurationDebuffTaken {
            get {
                return ResourceManager.GetString("ModDurationDebuffTaken", resourceCulture);
            }
        }
        
        public static string ModStacksBuffDealt {
            get {
                return ResourceManager.GetString("ModStacksBuffDealt", resourceCulture);
            }
        }
        
        public static string ModStacksBuffTaken {
            get {
                return ResourceManager.GetString("ModStacksBuffTaken", resourceCulture);
            }
        }
        
        public static string ModStacksDebuffDealt {
            get {
                return ResourceManager.GetString("ModStacksDebuffDealt", resourceCulture);
            }
        }
        
        public static string ModStacksDebuffTaken {
            get {
                return ResourceManager.GetString("ModStacksDebuffTaken", resourceCulture);
            }
        }
        
        public static string ModRange {
            get {
                return ResourceManager.GetString("ModRange", resourceCulture);
            }
        }
        
        public static string BoolEffectBlock {
            get {
                return ResourceManager.GetString("BoolEffectBlock", resourceCulture);
            }
        }
        
        public static string BoolInfiniteSp {
            get {
                return ResourceManager.GetString("BoolInfiniteSp", resourceCulture);
            }
        }
        
        public static string BoolUnableToAct {
            get {
                return ResourceManager.GetString("BoolUnableToAct", resourceCulture);
            }
        }
        
        public static string BoolUnableToActImmunity {
            get {
                return ResourceManager.GetString("BoolUnableToActImmunity", resourceCulture);
            }
        }
        
        public static string BoolEquipDisabled {
            get {
                return ResourceManager.GetString("BoolEquipDisabled", resourceCulture);
            }
        }
        
        public static string BoolEquipDisabledImmunity {
            get {
                return ResourceManager.GetString("BoolEquipDisabledImmunity", resourceCulture);
            }
        }
        
        public static string ExtraActions {
            get {
                return ResourceManager.GetString("ExtraActions", resourceCulture);
            }
        }
        
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        public static string Stages {
            get {
                return ResourceManager.GetString("Stages", resourceCulture);
            }
        }
        
        public static string Stage_S {
            get {
                return ResourceManager.GetString("Stage_S", resourceCulture);
            }
        }
        
        public static string StageAtk {
            get {
                return ResourceManager.GetString("StageAtk", resourceCulture);
            }
        }
        
        public static string StageAtkDesc {
            get {
                return ResourceManager.GetString("StageAtkDesc", resourceCulture);
            }
        }
        
        public static string StageDef {
            get {
                return ResourceManager.GetString("StageDef", resourceCulture);
            }
        }
        
        public static string StageDefDesc {
            get {
                return ResourceManager.GetString("StageDefDesc", resourceCulture);
            }
        }
        
        public static string StageFthDesc {
            get {
                return ResourceManager.GetString("StageFthDesc", resourceCulture);
            }
        }
        
        public static string StageAgiDesc {
            get {
                return ResourceManager.GetString("StageAgiDesc", resourceCulture);
            }
        }
        
        public static string SkillTypeStat {
            get {
                return ResourceManager.GetString("SkillTypeStat", resourceCulture);
            }
        }
        
        public static string SkillTypeStatFull {
            get {
                return ResourceManager.GetString("SkillTypeStatFull", resourceCulture);
            }
        }
        
        public static string RangeSelf {
            get {
                return ResourceManager.GetString("RangeSelf", resourceCulture);
            }
        }
        
        public static string RangeOther1r {
            get {
                return ResourceManager.GetString("RangeOther1r", resourceCulture);
            }
        }
        
        public static string RangeOther2r {
            get {
                return ResourceManager.GetString("RangeOther2r", resourceCulture);
            }
        }
        
        public static string RangeOther3r {
            get {
                return ResourceManager.GetString("RangeOther3r", resourceCulture);
            }
        }
        
        public static string RangeOther1rOrSelf {
            get {
                return ResourceManager.GetString("RangeOther1rOrSelf", resourceCulture);
            }
        }
        
        public static string RangeOther2rOrSelf {
            get {
                return ResourceManager.GetString("RangeOther2rOrSelf", resourceCulture);
            }
        }
        
        public static string RangeOther3rOrSelf {
            get {
                return ResourceManager.GetString("RangeOther3rOrSelf", resourceCulture);
            }
        }
        
        public static string RangeOthers21r {
            get {
                return ResourceManager.GetString("RangeOthers21r", resourceCulture);
            }
        }
        
        public static string RangeOthers22r {
            get {
                return ResourceManager.GetString("RangeOthers22r", resourceCulture);
            }
        }
        
        public static string RangeOthers23r {
            get {
                return ResourceManager.GetString("RangeOthers23r", resourceCulture);
            }
        }
        
        public static string RangeAlly1r {
            get {
                return ResourceManager.GetString("RangeAlly1r", resourceCulture);
            }
        }
        
        public static string RangeAlly2r {
            get {
                return ResourceManager.GetString("RangeAlly2r", resourceCulture);
            }
        }
        
        public static string RangeAlly3r {
            get {
                return ResourceManager.GetString("RangeAlly3r", resourceCulture);
            }
        }
        
        public static string RangeAllies21r {
            get {
                return ResourceManager.GetString("RangeAllies21r", resourceCulture);
            }
        }
        
        public static string RangeAllies22r {
            get {
                return ResourceManager.GetString("RangeAllies22r", resourceCulture);
            }
        }
        
        public static string RangeAllies23r {
            get {
                return ResourceManager.GetString("RangeAllies23r", resourceCulture);
            }
        }
        
        public static string RangeOpponent1r {
            get {
                return ResourceManager.GetString("RangeOpponent1r", resourceCulture);
            }
        }
        
        public static string RangeOpponent2r {
            get {
                return ResourceManager.GetString("RangeOpponent2r", resourceCulture);
            }
        }
        
        public static string RangeOpponent3r {
            get {
                return ResourceManager.GetString("RangeOpponent3r", resourceCulture);
            }
        }
        
        public static string RangeTeam {
            get {
                return ResourceManager.GetString("RangeTeam", resourceCulture);
            }
        }
        
        public static string RangeAll {
            get {
                return ResourceManager.GetString("RangeAll", resourceCulture);
            }
        }
        
        public static string RangeAllOthers {
            get {
                return ResourceManager.GetString("RangeAllOthers", resourceCulture);
            }
        }
        
        public static string RangeAdjacent {
            get {
                return ResourceManager.GetString("RangeAdjacent", resourceCulture);
            }
        }
        
        public static string RangeSelfUpDown {
            get {
                return ResourceManager.GetString("RangeSelfUpDown", resourceCulture);
            }
        }
        
        public static string RangeAcross {
            get {
                return ResourceManager.GetString("RangeAcross", resourceCulture);
            }
        }
        
        public static string RangeAcrossUpDown {
            get {
                return ResourceManager.GetString("RangeAcrossUpDown", resourceCulture);
            }
        }
        
        public static string RangeColumnOf31r {
            get {
                return ResourceManager.GetString("RangeColumnOf31r", resourceCulture);
            }
        }
        
        public static string RangeColumnOf32r {
            get {
                return ResourceManager.GetString("RangeColumnOf32r", resourceCulture);
            }
        }
        
        public static string LogGainSpBloom {
            get {
                return ResourceManager.GetString("LogGainSpBloom", resourceCulture);
            }
        }
        
        public static string LogChangeAff {
            get {
                return ResourceManager.GetString("LogChangeAff", resourceCulture);
            }
        }
        
        public static string LogChangeBloom {
            get {
                return ResourceManager.GetString("LogChangeBloom", resourceCulture);
            }
        }
        
        public static string LogChangeBooleanStatEffectBlock {
            get {
                return ResourceManager.GetString("LogChangeBooleanStatEffectBlock", resourceCulture);
            }
        }
        
        public static string LogChangeBooleanStatUnableToActImmune {
            get {
                return ResourceManager.GetString("LogChangeBooleanStatUnableToActImmune", resourceCulture);
            }
        }
        
        public static string LogChangeBooleanStatEquipDisabledImmune {
            get {
                return ResourceManager.GetString("LogChangeBooleanStatEquipDisabledImmune", resourceCulture);
            }
        }
        
        public static string LogChangeBooleanStatInfiniteSp {
            get {
                return ResourceManager.GetString("LogChangeBooleanStatInfiniteSp", resourceCulture);
            }
        }
        
        public static string LogChangeBooleanStatUnableToAct {
            get {
                return ResourceManager.GetString("LogChangeBooleanStatUnableToAct", resourceCulture);
            }
        }
        
        public static string LogChangeBooleanStatEquipDisabled {
            get {
                return ResourceManager.GetString("LogChangeBooleanStatEquipDisabled", resourceCulture);
            }
        }
        
        public static string LogChangeExtraActions {
            get {
                return ResourceManager.GetString("LogChangeExtraActions", resourceCulture);
            }
        }
        
        public static string LogChangeHp {
            get {
                return ResourceManager.GetString("LogChangeHp", resourceCulture);
            }
        }
        
        public static string LogChangeSp {
            get {
                return ResourceManager.GetString("LogChangeSp", resourceCulture);
            }
        }
        
        public static string LogChangeMod {
            get {
                return ResourceManager.GetString("LogChangeMod", resourceCulture);
            }
        }
        
        public static string LogChangeMultCalced {
            get {
                return ResourceManager.GetString("LogChangeMultCalced", resourceCulture);
            }
        }
        
        public static string LogChangeMultCalcedChange {
            get {
                return ResourceManager.GetString("LogChangeMultCalcedChange", resourceCulture);
            }
        }
        
        public static string LogChangeMultCalcedChangeDefault {
            get {
                return ResourceManager.GetString("LogChangeMultCalcedChangeDefault", resourceCulture);
            }
        }
        
        public static string LogChangeMult {
            get {
                return ResourceManager.GetString("LogChangeMult", resourceCulture);
            }
        }
        
        public static string LogChangeShield {
            get {
                return ResourceManager.GetString("LogChangeShield", resourceCulture);
            }
        }
        
        public static string LogChangeStageStacks {
            get {
                return ResourceManager.GetString("LogChangeStageStacks", resourceCulture);
            }
        }
        
        public static string LogChangeStageTurns {
            get {
                return ResourceManager.GetString("LogChangeStageTurns", resourceCulture);
            }
        }
        
        public static string LogChangeStat {
            get {
                return ResourceManager.GetString("LogChangeStat", resourceCulture);
            }
        }
        
        public static string LogGiveBuffStacks {
            get {
                return ResourceManager.GetString("LogGiveBuffStacks", resourceCulture);
            }
        }
        
        public static string LogGiveBuffTurns {
            get {
                return ResourceManager.GetString("LogGiveBuffTurns", resourceCulture);
            }
        }
        
        public static string LogGiveBuffGain {
            get {
                return ResourceManager.GetString("LogGiveBuffGain", resourceCulture);
            }
        }
        
        public static string LogStackS {
            get {
                return ResourceManager.GetString("LogStackS", resourceCulture);
            }
        }
        
        public static string LogLoseBuff {
            get {
                return ResourceManager.GetString("LogLoseBuff", resourceCulture);
            }
        }
        
        public static string LogLoseStage {
            get {
                return ResourceManager.GetString("LogLoseStage", resourceCulture);
            }
        }
        
        public static string LogLoseShield {
            get {
                return ResourceManager.GetString("LogLoseShield", resourceCulture);
            }
        }
        
        public static string LogShieldTurns {
            get {
                return ResourceManager.GetString("LogShieldTurns", resourceCulture);
            }
        }
        
        public static string LogStageStat {
            get {
                return ResourceManager.GetString("LogStageStat", resourceCulture);
            }
        }
        
        public static string LogTurnEndEffect {
            get {
                return ResourceManager.GetString("LogTurnEndEffect", resourceCulture);
            }
        }
        
        public static string LogTurnsNameless {
            get {
                return ResourceManager.GetString("LogTurnsNameless", resourceCulture);
            }
        }
        
        public static string LogSkillUse {
            get {
                return ResourceManager.GetString("LogSkillUse", resourceCulture);
            }
        }
        
        public static string LogSkillUseChangeSpBloom {
            get {
                return ResourceManager.GetString("LogSkillUseChangeSpBloom", resourceCulture);
            }
        }
        
        public static string LogNoEffect {
            get {
                return ResourceManager.GetString("LogNoEffect", resourceCulture);
            }
        }
        
        public static string LogTriesToUse1 {
            get {
                return ResourceManager.GetString("LogTriesToUse1", resourceCulture);
            }
        }
        
        public static string LogTriesToUse2 {
            get {
                return ResourceManager.GetString("LogTriesToUse2", resourceCulture);
            }
        }
        
        public static string LogButIsUnableToAct {
            get {
                return ResourceManager.GetString("LogButIsUnableToAct", resourceCulture);
            }
        }
        
        public static string LogSkillFailUnableToAct {
            get {
                return ResourceManager.GetString("LogSkillFailUnableToAct", resourceCulture);
            }
        }
        
        public static string LogButItsOnCooldown {
            get {
                return ResourceManager.GetString("LogButItsOnCooldown", resourceCulture);
            }
        }
        
        public static string LogSkillFailCooldown {
            get {
                return ResourceManager.GetString("LogSkillFailCooldown", resourceCulture);
            }
        }
        
        public static string LogButCantReach {
            get {
                return ResourceManager.GetString("LogButCantReach", resourceCulture);
            }
        }
        
        public static string LogSkillFailRange {
            get {
                return ResourceManager.GetString("LogSkillFailRange", resourceCulture);
            }
        }
        
        public static string LogButDoesntHaveEnough {
            get {
                return ResourceManager.GetString("LogButDoesntHaveEnough", resourceCulture);
            }
        }
        
        public static string LogSkillFailSp {
            get {
                return ResourceManager.GetString("LogSkillFailSp", resourceCulture);
            }
        }
        
        public static string SkillCost {
            get {
                return ResourceManager.GetString("SkillCost", resourceCulture);
            }
        }
        
        public static string SkillDesc {
            get {
                return ResourceManager.GetString("SkillDesc", resourceCulture);
            }
        }
        
        public static string SkillDescBuff {
            get {
                return ResourceManager.GetString("SkillDescBuff", resourceCulture);
            }
        }
        
        public static string SkillDescBuff2SameTurns {
            get {
                return ResourceManager.GetString("SkillDescBuff2SameTurns", resourceCulture);
            }
        }
        
        public static string SkillDescMultihitBuff {
            get {
                return ResourceManager.GetString("SkillDescMultihitBuff", resourceCulture);
            }
        }
        
        public static string SkillNothing {
            get {
                return ResourceManager.GetString("SkillNothing", resourceCulture);
            }
        }
        
        public static string SkillDefend {
            get {
                return ResourceManager.GetString("SkillDefend", resourceCulture);
            }
        }
        
        public static string SkillProtect {
            get {
                return ResourceManager.GetString("SkillProtect", resourceCulture);
            }
        }
        
        public static string SkillBlossom {
            get {
                return ResourceManager.GetString("SkillBlossom", resourceCulture);
            }
        }
        
        public static string SkillAtkUp {
            get {
                return ResourceManager.GetString("SkillAtkUp", resourceCulture);
            }
        }
        
        public static string SkillAtkDown {
            get {
                return ResourceManager.GetString("SkillAtkDown", resourceCulture);
            }
        }
        
        public static string SkillDefUp {
            get {
                return ResourceManager.GetString("SkillDefUp", resourceCulture);
            }
        }
        
        public static string SkillDefDown {
            get {
                return ResourceManager.GetString("SkillDefDown", resourceCulture);
            }
        }
        
        public static string SkillFthUp {
            get {
                return ResourceManager.GetString("SkillFthUp", resourceCulture);
            }
        }
        
        public static string SkillFthDown {
            get {
                return ResourceManager.GetString("SkillFthDown", resourceCulture);
            }
        }
        
        public static string SkillAgiUp {
            get {
                return ResourceManager.GetString("SkillAgiUp", resourceCulture);
            }
        }
        
        public static string SkillAgiDown {
            get {
                return ResourceManager.GetString("SkillAgiDown", resourceCulture);
            }
        }
        
        public static string SkillAtkUpGroup {
            get {
                return ResourceManager.GetString("SkillAtkUpGroup", resourceCulture);
            }
        }
        
        public static string SkillAtkDownGroup {
            get {
                return ResourceManager.GetString("SkillAtkDownGroup", resourceCulture);
            }
        }
        
        public static string SkillDefUpGroup {
            get {
                return ResourceManager.GetString("SkillDefUpGroup", resourceCulture);
            }
        }
        
        public static string SkillDefDownGroup {
            get {
                return ResourceManager.GetString("SkillDefDownGroup", resourceCulture);
            }
        }
        
        public static string SkillFthUpGroup {
            get {
                return ResourceManager.GetString("SkillFthUpGroup", resourceCulture);
            }
        }
        
        public static string SkillFthDownGroup {
            get {
                return ResourceManager.GetString("SkillFthDownGroup", resourceCulture);
            }
        }
        
        public static string SkillAgiUpGroup {
            get {
                return ResourceManager.GetString("SkillAgiUpGroup", resourceCulture);
            }
        }
        
        public static string SkillAgiDownGroup {
            get {
                return ResourceManager.GetString("SkillAgiDownGroup", resourceCulture);
            }
        }
        
        public static string SkillHeal {
            get {
                return ResourceManager.GetString("SkillHeal", resourceCulture);
            }
        }
        
        public static string SkillAmbrosia {
            get {
                return ResourceManager.GetString("SkillAmbrosia", resourceCulture);
            }
        }
        
        public static string SkillHealGroup {
            get {
                return ResourceManager.GetString("SkillHealGroup", resourceCulture);
            }
        }
        
        public static string SkillShield {
            get {
                return ResourceManager.GetString("SkillShield", resourceCulture);
            }
        }
        
        public static string SkillShieldGroup {
            get {
                return ResourceManager.GetString("SkillShieldGroup", resourceCulture);
            }
        }
        
        public static string SkillFireball {
            get {
                return ResourceManager.GetString("SkillFireball", resourceCulture);
            }
        }
        
        public static string SkillHeatWave {
            get {
                return ResourceManager.GetString("SkillHeatWave", resourceCulture);
            }
        }
        
        public static string SkillIceBeam {
            get {
                return ResourceManager.GetString("SkillIceBeam", resourceCulture);
            }
        }
        
        public static string SkillThunderbolt {
            get {
                return ResourceManager.GetString("SkillThunderbolt", resourceCulture);
            }
        }
        
        public static string SkillJetStream {
            get {
                return ResourceManager.GetString("SkillJetStream", resourceCulture);
            }
        }
        
        public static string SkillDemonScythe {
            get {
                return ResourceManager.GetString("SkillDemonScythe", resourceCulture);
            }
        }
        
        public static string SkillIceAge {
            get {
                return ResourceManager.GetString("SkillIceAge", resourceCulture);
            }
        }
        
        public static string BuffDesc {
            get {
                return ResourceManager.GetString("BuffDesc", resourceCulture);
            }
        }
        
        public static string BuffDescStacksTo {
            get {
                return ResourceManager.GetString("BuffDescStacksTo", resourceCulture);
            }
        }
        
        public static string BuffDesc1 {
            get {
                return ResourceManager.GetString("BuffDesc1", resourceCulture);
            }
        }
        
        public static string BuffDesc2 {
            get {
                return ResourceManager.GetString("BuffDesc2", resourceCulture);
            }
        }
        
        public static string BuffDesc1PerStack {
            get {
                return ResourceManager.GetString("BuffDesc1PerStack", resourceCulture);
            }
        }
        
        public static string BuffDesc2PerStack {
            get {
                return ResourceManager.GetString("BuffDesc2PerStack", resourceCulture);
            }
        }
        
        public static string BuffDesc2PerStackHp {
            get {
                return ResourceManager.GetString("BuffDesc2PerStackHp", resourceCulture);
            }
        }
        
        public static string BuffDefend {
            get {
                return ResourceManager.GetString("BuffDefend", resourceCulture);
            }
        }
        
        public static string BuffShield {
            get {
                return ResourceManager.GetString("BuffShield", resourceCulture);
            }
        }
        
        public static string BuffProtect {
            get {
                return ResourceManager.GetString("BuffProtect", resourceCulture);
            }
        }
        
        public static string BuffStunned {
            get {
                return ResourceManager.GetString("BuffStunned", resourceCulture);
            }
        }
        
        public static string BuffBurn {
            get {
                return ResourceManager.GetString("BuffBurn", resourceCulture);
            }
        }
        
        public static string BuffFrostbite {
            get {
                return ResourceManager.GetString("BuffFrostbite", resourceCulture);
            }
        }
        
        public static string BuffShock {
            get {
                return ResourceManager.GetString("BuffShock", resourceCulture);
            }
        }
        
        public static string BuffWindswept {
            get {
                return ResourceManager.GetString("BuffWindswept", resourceCulture);
            }
        }
        
        public static string BuffTremor {
            get {
                return ResourceManager.GetString("BuffTremor", resourceCulture);
            }
        }
        
        public static string BuffDazzled {
            get {
                return ResourceManager.GetString("BuffDazzled", resourceCulture);
            }
        }
        
        public static string BuffCurse {
            get {
                return ResourceManager.GetString("BuffCurse", resourceCulture);
            }
        }
        
        public static string BuffPoison {
            get {
                return ResourceManager.GetString("BuffPoison", resourceCulture);
            }
        }
        
        public static string BuffRadiation {
            get {
                return ResourceManager.GetString("BuffRadiation", resourceCulture);
            }
        }
        
        public static string BuffBurntOut {
            get {
                return ResourceManager.GetString("BuffBurntOut", resourceCulture);
            }
        }
        
        public static string BuffFrostbound {
            get {
                return ResourceManager.GetString("BuffFrostbound", resourceCulture);
            }
        }
        
        public static string BuffOverloaded {
            get {
                return ResourceManager.GetString("BuffOverloaded", resourceCulture);
            }
        }
        
        public static string BuffTempest {
            get {
                return ResourceManager.GetString("BuffTempest", resourceCulture);
            }
        }
        
        public static string BuffShattered {
            get {
                return ResourceManager.GetString("BuffShattered", resourceCulture);
            }
        }
        
        public static string BuffStarstruck {
            get {
                return ResourceManager.GetString("BuffStarstruck", resourceCulture);
            }
        }
        
        public static string BuffDoomed {
            get {
                return ResourceManager.GetString("BuffDoomed", resourceCulture);
            }
        }
        
        public static string BuffBlighted {
            get {
                return ResourceManager.GetString("BuffBlighted", resourceCulture);
            }
        }
        
        public static string BuffDecay {
            get {
                return ResourceManager.GetString("BuffDecay", resourceCulture);
            }
        }
        
        public static string BuffRegeneration {
            get {
                return ResourceManager.GetString("BuffRegeneration", resourceCulture);
            }
        }
        
        public static string BuffRegenerationDesc {
            get {
                return ResourceManager.GetString("BuffRegenerationDesc", resourceCulture);
            }
        }
        
        public static string BuffExtraAction {
            get {
                return ResourceManager.GetString("BuffExtraAction", resourceCulture);
            }
        }
        
        public static string BuffExtraActionDesc {
            get {
                return ResourceManager.GetString("BuffExtraActionDesc", resourceCulture);
            }
        }
        
        public static string PassiveRestoration {
            get {
                return ResourceManager.GetString("PassiveRestoration", resourceCulture);
            }
        }
        
        public static string PassiveRestorationDesc {
            get {
                return ResourceManager.GetString("PassiveRestorationDesc", resourceCulture);
            }
        }
        
        public static string PassiveIgnisAffUp {
            get {
                return ResourceManager.GetString("PassiveIgnisAffUp", resourceCulture);
            }
        }
        
        public static string PassiveIgnisAffUpDesc {
            get {
                return ResourceManager.GetString("PassiveIgnisAffUpDesc", resourceCulture);
            }
        }
        
        public static string PassivePercentageDmgTakenDown50 {
            get {
                return ResourceManager.GetString("PassivePercentageDmgTakenDown50", resourceCulture);
            }
        }
        
        public static string PassivePercentageDmgTakenDown50Desc {
            get {
                return ResourceManager.GetString("PassivePercentageDmgTakenDown50Desc", resourceCulture);
            }
        }
        
        public static string PassivePercentageDmgTakenDown999 {
            get {
                return ResourceManager.GetString("PassivePercentageDmgTakenDown999", resourceCulture);
            }
        }
        
        public static string PassivePercentageDmgTakenDown999Desc {
            get {
                return ResourceManager.GetString("PassivePercentageDmgTakenDown999Desc", resourceCulture);
            }
        }
        
        public static string PassiveBuffDurationUp {
            get {
                return ResourceManager.GetString("PassiveBuffDurationUp", resourceCulture);
            }
        }
        
        public static string PassiveBuffDurationUpDesc {
            get {
                return ResourceManager.GetString("PassiveBuffDurationUpDesc", resourceCulture);
            }
        }
        
        public static string PassiveDebuffDurationUp {
            get {
                return ResourceManager.GetString("PassiveDebuffDurationUp", resourceCulture);
            }
        }
        
        public static string PassiveDebuffDurationUpDesc {
            get {
                return ResourceManager.GetString("PassiveDebuffDurationUpDesc", resourceCulture);
            }
        }
        
        public static string PassiveEternalWellspring {
            get {
                return ResourceManager.GetString("PassiveEternalWellspring", resourceCulture);
            }
        }
        
        public static string PassiveEternalWellspringDesc {
            get {
                return ResourceManager.GetString("PassiveEternalWellspringDesc", resourceCulture);
            }
        }
        
        public static string AccessoryDesc {
            get {
                return ResourceManager.GetString("AccessoryDesc", resourceCulture);
            }
        }
        
        public static string AccessoryFirebornRing {
            get {
                return ResourceManager.GetString("AccessoryFirebornRing", resourceCulture);
            }
        }
        
        public static string TutorialDamage {
            get {
                return ResourceManager.GetString("TutorialDamage", resourceCulture);
            }
        }
        
        public static string TutorialDamageDesc {
            get {
                return ResourceManager.GetString("TutorialDamageDesc", resourceCulture);
            }
        }
        
        public static string InfoStat {
            get {
                return ResourceManager.GetString("InfoStat", resourceCulture);
            }
        }
        
        public static string InfoStatDesc {
            get {
                return ResourceManager.GetString("InfoStatDesc", resourceCulture);
            }
        }
        
        public static string InfoAffinity {
            get {
                return ResourceManager.GetString("InfoAffinity", resourceCulture);
            }
        }
        
        public static string InfoAffinityDesc {
            get {
                return ResourceManager.GetString("InfoAffinityDesc", resourceCulture);
            }
        }
        
        public static string InfoMult {
            get {
                return ResourceManager.GetString("InfoMult", resourceCulture);
            }
        }
        
        public static string InfoMultDesc {
            get {
                return ResourceManager.GetString("InfoMultDesc", resourceCulture);
            }
        }
        
        public static string InfoMod {
            get {
                return ResourceManager.GetString("InfoMod", resourceCulture);
            }
        }
        
        public static string InfoModDesc {
            get {
                return ResourceManager.GetString("InfoModDesc", resourceCulture);
            }
        }
        
        public static string InfoOther {
            get {
                return ResourceManager.GetString("InfoOther", resourceCulture);
            }
        }
        
        public static string InfoOtherDesc {
            get {
                return ResourceManager.GetString("InfoOtherDesc", resourceCulture);
            }
        }
        
        public static string WarningInvalidMove {
            get {
                return ResourceManager.GetString("WarningInvalidMove", resourceCulture);
            }
        }
        
        public static string WarningInvalidMoveDesc {
            get {
                return ResourceManager.GetString("WarningInvalidMoveDesc", resourceCulture);
            }
        }
        
        public static string WarningInvalidMoveIsOutOfRange {
            get {
                return ResourceManager.GetString("WarningInvalidMoveIsOutOfRange", resourceCulture);
            }
        }
        
        public static string WarningInvalidMoveDoesntHaveEnough {
            get {
                return ResourceManager.GetString("WarningInvalidMoveDoesntHaveEnough", resourceCulture);
            }
        }
    }
}
